---
- name: Restart systemd-timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted

- name: Restart Docker daemon
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: Regenerate locale
  ansible.builtin.command: locale-gen
  changed_when: true

- name: Refresh apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Systemd daemon reload
  ansible.builtin.systemd:
    daemon_reload: true
  changed_when: true

- name: netplan apply
  command: netplan apply

- name: Restart Husarnet
  ansible.builtin.systemd:
    name: husarnet
    state: restarted

- name: Apply sysctl
  command: sysctl --system
