ARG ROS_DISTRO=jazzy
ARG PREFIX=

FROM husarnet/ros:${PREFIX}${ROS_DISTRO}-ros-core

RUN apt update && apt install -y \
      ros-${ROS_DISTRO}-cyclonedds \
      ros-${ROS_DISTRO}-zstd-point-cloud-transport \
      ros-${ROS_DISTRO}-draco-point-cloud-transport && \
    apt clean &&  \
    rm -rf /var/lib/apt/lists/*
