---
- name: Install docker and docker compose
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  tags: packages

- name: Add Docker permissions to Teams user
  ansible.builtin.user:
    name: "{{ teams_user }}"
    groups: docker
    append: true
  tags: users
