---
- name: Add keys for Husarnet repository
  ansible.builtin.apt_key:
    url: "https://nightly.husarnet.com/repo.key"
    state: present
  tags: apt

- name: Add Husarnet Nightly APT repository
  ansible.builtin.apt_repository:
    repo: "deb https://nightly.husarnet.com/deb/ all husarnet"
    filename: husarnet
    state: present
  tags: apt

- name: Add Husarnet Nightly APT repository
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    filename: husarnet
    state: absent
  with_items:
    - deb [signed-by=/usr/share/keyrings/husarnet.gpg] https://install.husarnet.com/deb/ all husarnet
    - deb [signed-by=/usr/share/keyrings/husarnet.gpg] https://install.husarnet.com/deb all husarnet
    - deb https://install.husarnet.com/deb/ all husarnet
    - deb https://nightly.husarnet.com/deb all husarnet
  tags: apt

- name: Flush handlers before continuing
  ansible.builtin.meta: flush_handlers

- name: Install Husarnet Daemon
  ansible.builtin.apt:
    pkg:
      - husarnet
    state: latest
  tags: packages

- name: Start and enable Husarnet in systemd
  ansible.builtin.systemd:
    name: husarnet
    enabled: true
    state: started
  tags: services

- name: Configure Husarnet to use Beta
  ansible.builtin.copy:
    dest: /etc/default/husarnet
    content: |
      HUSARNET_INSTANCE_FQDN=beta.husarnet.com
  notify:
    - Restart Husarnet
